In [2]:
import numpy as np

arr1 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Array 1:")
print(arr1)

print("\nArray 2:")
print(arr2)

print("\nAccessing Elements")
print("First element:", arr1[0, 0])
print("Center element:", arr1[1, 1])
print("Last element:", arr1[2, 2])

print("\nAddition")
print(arr1 + arr2)

print("\nSubtraction")
print(arr1 - arr2)

print("\nMultiplication")
print(arr1 * arr2)

print("\nDivision")
print(arr1 / arr2)

print("\n1. Shape")
print(arr1.shape)

print("\n2. Dimensions (ndim)")
print(arr1.ndim)

print("\n3. Size")
print(arr1.size)

print("\n4. Data Type")
print(arr1.dtype)

print("\n5. Reshape")
print(arr1.reshape(1, 9))

print("\n6. Flatten")
print(arr1.flatten())

print("\n7. Transpose")
print(arr1.T)

print("\n8. Maximum")
print(np.max(arr1))

print("\n9. Minimum")
print(np.min(arr1))

print("\n10. Sum")
print(np.sum(arr1))

print("\n11. Mean")
print(np.mean(arr1))

print("\n12. Median")
print(np.median(arr1))

print("\n13. Standard Deviation")
print(np.std(arr1))

print("\n14. Sort")
print(np.sort(arr1))

print("\n15. Unique Values")
print(np.unique(arr1))

Array 1:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Array 2:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Accessing Elements
First element: 10
Center element: 50
Last element: 90

Addition
[[11 22 33]
 [44 55 66]
 [77 88 99]]

Subtraction
[[ 9 18 27]
 [36 45 54]
 [63 72 81]]

Multiplication
[[ 10  40  90]
 [160 250 360]
 [490 640 810]]

Division
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]

1. Shape
(3, 3)

2. Dimensions (ndim)
2

3. Size
9

4. Data Type
int64

5. Reshape
[[10 20 30 40 50 60 70 80 90]]

6. Flatten
[10 20 30 40 50 60 70 80 90]

7. Transpose
[[10 40 70]
 [20 50 80]
 [30 60 90]]

8. Maximum
90

9. Minimum
10

10. Sum
450

11. Mean
50.0

12. Median
50.0

13. Standard Deviation
25.81988897471611

14. Sort
[[10 20 30]
 [40 50 60]
 [70 80 90]]

15. Unique Values
[10 20 30 40 50 60 70 80 90]
